compressionLevel: 0

defaultSemverRangePrefix: ^

enableGlobalCache: false

enableMessageNames: false

nodeLinker: node-modules

plugins:
  - checksum: 729dece8851646b1cf50896d8bd7fca5c9204a1cde56ad25678881fc8d9ad9bb58e25472fbc0053d69160c6f0ec998341c83606729faa2a4d91e45f0e50bbc7c
    path: .yarn/plugins/@yarnpkg/plugin-conventional-version.cjs
    spec: "https://raw.githubusercontent.com/christophehurpeau/yarn-plugin-conventional-version/main/bundles/@yarnpkg/plugin-conventional-version.cjs"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
